"use client";

import { GlassCard } from '@/components/ui/GlassCard';
import { Logo } from '@/components/ui/Logo';
import Link from 'next/link';

export default function TermsPage() {
    return (
        <div className="min-h-screen flex flex-col items-center justify-center p-6 relative overflow-hidden bg-[#030712] text-gray-300">
            {/* Background Elements */}
            <div className="fixed inset-0 pointer-events-none">
                <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] bg-purple-500/10 rounded-full blur-[100px]" />
            </div>

            <nav className="absolute top-0 left-0 right-0 p-6 flex justify-between items-center z-50 max-w-7xl mx-auto w-full">
                <Link href="/">
                    <Logo size="large" />
                </Link>
                <Link href="/" className="text-gray-400 hover:text-white transition-colors">
                    Home
                </Link>
            </nav>

            <main className="max-w-4xl w-full z-10 pt-32 pb-16">
                <GlassCard className="p-8 md:p-12 bg-white/5 border-white/10">
                    <h1 className="text-3xl font-bold text-white mb-8 border-b border-white/10 pb-4">Terms of Service (이용약관)</h1>

                    <div className="space-y-6 text-sm leading-relaxed">
                        <section>
                            <h2 className="text-xl font-semibold text-blue-400 mb-2">1. Introduction (소개)</h2>
                            <p>Welcome to TRNT (The Road Not Taken). These Terms of Service govern your use of our AI-powered parallel world simulation service.</p>
                            <p className="mt-2 text-gray-500">TRNT에 오신 것을 환영합니다. 본 약관은 TRNT의 AI 기반 평행세계 시뮬레이션 서비스 이용에 관한 규정을 담고 있습니다.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-blue-400 mb-2">2. User Accounts (계정)</h2>
                            <p>To access certain features, you must register for an account. You are responsible for maintaining the confidentiality of your account credentials.</p>
                            <p className="mt-2 text-gray-500">일부 기능을 이용하기 위해서는 계정 등록이 필요합니다. 계정 정보의 보안 유지 책임은 사용자에게 있습니다.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-blue-400 mb-2">3. Acceptable Use (허용된 이용)</h2>
                            <p>You agree not to misuse our services or generate content that is illegal, harmful, or violates the rights of others.</p>
                            <p className="mt-2 text-gray-500">서비스를 오남용하거나 불법적, 유해한 콘텐츠를 생성하지 않는 것에 동의합니다.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-blue-400 mb-2">4. AI-Generated Content (AI 생성 콘텐츠)</h2>
                            <p>Content generated by TRNT is for entertainment and self-reflection purposes only. We do not guarantee the accuracy or reliability of the generated narratives.</p>
                            <p className="mt-2 text-gray-500">TRNT가 생성한 콘텐츠는 엔터테인먼트 및 자기 성찰 목적입니다. 생성된 이야기의 정확성이나 신뢰성을 보장하지 않습니다.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-blue-400 mb-2">5. Termination (서비스 종료)</h2>
                            <p>We reserve the right to suspend or terminate your access to the service at our sole discretion, without notice, for conduct that we believe violates these Terms.</p>
                            <p className="mt-2 text-gray-500">약관 위반 시 사전 고지 없이 서비스 이용을 중단하거나 해지할 수 있습니다.</p>
                        </section>
                    </div>
                </GlassCard>
            </main>

            <footer className="w-full max-w-7xl mx-auto py-8 text-center text-gray-500 text-sm border-t border-white/5">
                <p>© 2026 TRNT Team. All rights reserved.</p>
            </footer>
        </div>
    );
}
