"""create users table

Revision ID: 5c18d2b79536
Revises: 
Create Date: 2026-02-03 15:16:35.803319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c18d2b79536'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('residence', sa.String(length=100), nullable=True),
    sa.Column('relationship_status', sa.String(length=50), nullable=True),
    sa.Column('life_background', sa.Text(), nullable=False),
    sa.Column('key_events', sa.Text(), nullable=True),
    sa.Column('personality', sa.String(length=100), nullable=True),
    sa.Column('values', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
