"""add_auth_columns_to_users

Revision ID: cb7ac7fcdfe0
Revises: 9520a2313ac5
Create Date: 2026-02-04 16:08:39.906805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7ac7fcdfe0'
down_revision: Union[str, None] = '9520a2313ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('kakao_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2. Update existing rows with default values
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")

    # 3. Alter columns to be NOT NULL
    op.alter_column('users', 'auth_provider', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)

    # 4. Create unique constraint
    op.create_unique_constraint(None, 'users', ['kakao_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'kakao_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
